module.exports = [
  { q:"HOW MANY DB INTEGRATIONS CONNECTED TO ELIS ?", o:["3","4","5","6"], a:3 },
  { q:"WHAT IS THE MAX.SIZE OF SMALL ADVANCE BATCH ACTIVATION IN ELIS ?", o:["29","39","19","9"], a:1 },
  { q:"ELIS TEAM IS SPREAD ACROSS LOCATIONS. HOW MANY LOCATIONS ARE THEY ? (DON’T COUNT YOUR HOME LOCATION :-p)", o:["4","5","6","7"], a:1 },
  { q:"HOW MANY P1 TICKETS DID ELIS RECEIVED IN 2025 ?", o:["1","2","3","0"], a:3 },
  { q:"WHAT IS THE LAST SPRINT NUMBER FOR ELIS IN 2025 ?", o:["64","66","65","61"], a:2 },
  { q:"BELOW MODULE DOESN’T EXIST IN SAM ?", o:["IL MANAGER","SSP","LKM PORTAL","SHM"], a:3 },
  { q:"HOW MANY PRICE MODELS EXIST IN IL FLOW ?", o:["2","3","4","1"], a:1 }
];
